# Generated by Django 5.1.2 on 2025-03-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa producenta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis producenta')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis kategorii')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.productcategory')),
            ],
            options={
                'verbose_name': 'Kategoria produktów',
                'verbose_name_plural': 'Kategorie produktów',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nazwa produktu', max_length=255, verbose_name='Nazwa produktu')),
                ('description', models.TextField(default='Opis produktu', verbose_name='Opis produktu')),
                ('application', models.TextField(blank=True, null=True, verbose_name='Zastosowanie')),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Moc (W)')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wymiary (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waga (kg)')),
                ('operating_temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Temperatura pracy')),
                ('protection_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='Klasa ochrony')),
                ('power_tolerance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tolerancja mocy (%)')),
                ('price_net_no_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena netto bez marży')),
                ('price_gross_no_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena brutto bez marży')),
                ('price_net_with_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena netto z marżą')),
                ('price_gross_with_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena brutto z marżą')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kraj pochodzenia')),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='Okres gwarancji')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Funkcje i zalety')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stan magazynowy')),
                ('out_of_stock', models.BooleanField(default=False, verbose_name='Brak w magazynie')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('structured_data', models.JSONField(blank=True, null=True, verbose_name='Structured Data')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on Homepage')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Promotion')),
                ('is_sponsored', models.BooleanField(default=False, verbose_name='Sponsored')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.manufacturer')),
                ('categories', models.ManyToManyField(related_name='products', to='product.productcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products', verbose_name='Plik')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.product')),
            ],
            options={
                'verbose_name': 'Plik produktu',
                'verbose_name_plural': 'Pliki produktów',
                'ordering': ['-product'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Zdjęcie produktu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Zdjęcie produktu',
                'verbose_name_plural': 'Zdjęcia produktów',
                'ordering': ['-product'],
            },
        ),
    ]
